# the program make will try to find a file called Makefile in the directory
#
# all : clean speicify the all block is depend on the clean block.
# so it will run make clean first.
# then it will run make all
all: clean
	clang -Wall -g ex02.c -o ex02
clean:
	rm -rf ex02
